server:
  port: 9090
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/operis
    username: root
    password: password
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret:
    code: 98562gfdijnglkndfklg+8945445g45eg45

logging:
  level:
    root: info
    ci.operis: info