spring:
  application:
    name: operis-discovery

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false # Don't register himself
    fetch-registry: false # Don't fetch registry from other services
